// App
export const MAIN_CURTAIN_OPENED = 'MAIN_CURTAIN_OPENED';

// Navbar
export const SET_NAVBAR_ELT = 'SET_NAVBAR_ELT';
export const NAVBAR_LOADED = 'NAVBAR_LOADED';
export const SET_BG_LOADED = 'SET_BG_LOADED';
export const SET_IMGS_LOADED = 'SET_IMGS_LOADED';
export const SET_PAGE_VISITED = 'SET_PAGE_VISITED';
export const NAVBAR_STICKY = 'NAVBAR_STICKY';
export const SCROLLABLE_ANCESTOR = 'SCROLLABLE_ANCESTOR';

// Menu
export const SET_MENU_CATEGORY = 'SET_MENU_CATEGORY';
export const MENU_VEIL_IN_POSITION = 'MENU_VEIL_IN_POSITION';
export const MENU_IN_TRANSITION = 'MENU_IN_TRANSITION';
export const SCROLL_TO_CATEGORY = 'SCROLL_TO_CATEGORY';


// Home
export const HOME_LOWER_LEFT_IN_POSITION = 'HOME_LOWER_LEFT_IN_POSITION';